### ISSUE TITLE
url broken in setup_params

### ISSUE THREAD

**Issue by JnyJny** [rubble/pybble#1]
There is an embedded space in the url specified in the file **pybble/**init**.py**.

```
19   'url': 'https: //github.com/viditeck/pybble',
```

This is causing a broken link on pypitest.python.org.

**Comment by EmlynC** [comment]
Nice catch. Fixing now.

**Comment by traceywright** [comment]
Do we communicate the fix to the user? 

Tracey Wright
Tel: +44 7809 701224
Skype: tcwright2

**Comment by EmlynC** [comment]
It's done. The message is from a github issue and I've replied to it on github and referenced the code that fixes it.
Emlyn
On 27 Oct 2015 5:54 p.m., traceywright notifications@github.com wrote:Do we communicate the fix to the user? 

Tracey Wright
Tel: +44 7809 701224
Skype: tcwright2

**Comment by JnyJny** [comment]
Glad to help.
